-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfdal60tjskIc3gHa
ULwZFqTeSlUFCOnQll/v7P77+1qgCgYIKoZIzj0DAQehRANCAAR1zAC/DpOzLM5m
Hq8s4DiN6F5ujTChJhFr5a3QYmggeZURCKLTYeZB7/LZIgUZ4aPYPyKouU/Zs+vD
CI8mhYP7
-----END PRIVATE KEY-----
