import React, { useState, useEffect, useRef } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
import { Button } from './ui/button'
import { useAuth } from '../contexts/AuthContext'
import { supabase } from '../utils/supabase/client'
import { AgoraService } from '../utils/agora'
import { Users, Volume2, VolumeX } from 'lucide-react'

interface ActiveStream {
  id: string
  channel: string
  title: string
  scholarName: string
  scholarId: string
  viewerCount: number
  startedAt: string
}

export const UserPrayerServiceViewer: React.FC = () => {
  const { profile } = useAuth()
  const [activeStreams, setActiveStreams] = useState<ActiveStream[]>([])
  const [selectedStream, setSelectedStream] = useState<ActiveStream | null>(null)
  const [isConnected, setIsConnected] = useState(false)
  const [audioEnabled, setAudioEnabled] = useState(true)
  const [error, setError] = useState('')
  
  const agoraService = useRef<AgoraService | null>(null)
  const remoteVideoRef = useRef<HTMLDivElement>(null)

  // Fetch active streams
  useEffect(() => {
    fetchActiveStreams()
    const interval = setInterval(fetchActiveStreams, 10000) // Refresh every 10 seconds
    return () => clearInterval(interval)
  }, [])

  const fetchActiveStreams = async () => {
    try {
      // TODO: Replace with actual API call
      // const response = await apiCall('active-streams')
      // setActiveStreams(response.streams)
      
      // Mock data for now
      setActiveStreams([
        {
          id: '1',
          channel: 'stream_scholar_123',
          title: 'Friday Jummah Prayer',
          scholarName: 'Imam Abdullah',
          scholarId: 'scholar_123',
          viewerCount: 45,
          startedAt: new Date().toISOString(),
        },
      ])
    } catch (err) {
      console.error('Error fetching streams:', err)
    }
  }

  const joinStream = async (stream: ActiveStream) => {
    setError('')
    setSelectedStream(stream)

    try {
      // Initialize Agora service
      agoraService.current = new AgoraService()

      // Join channel as audience (with token generation)
      await agoraService.current.joinChannel({
        appId: import.meta.env.VITE_AGORA_APP_ID || '',
        channel: stream.channel,
        token: null, // Token will be generated by joinChannel
        uid: profile?.id || '',
      }, 'audience') // Specify role as 'audience'

      // Subscribe to remote streams
      agoraService.current.onUserPublished(async (user, mediaType) => {
        try {
          const track = await agoraService.current!.subscribeToUser(user, mediaType)
          
          if (mediaType === 'video' && remoteVideoRef.current) {
            (track as any).play(remoteVideoRef.current)
          }
        } catch (err) {
          console.error('Error subscribing to user:', err)
        }
      })

      setIsConnected(true)

      // Track participant in database
      await supabase.from('stream_participants').insert({
        stream_id: stream.id,
        user_id: profile?.id,
        is_active: true
      })

    } catch (err: any) {
      console.error('Error joining stream:', err)
      setError(err.message || 'Failed to join stream')
    }
  }

  const leaveStream = async () => {
    try {
      if (agoraService.current) {
        await agoraService.current.leaveChannel()
        agoraService.current = null
      }

      // Update participant record in database
      if (selectedStream) {
        await supabase
          .from('stream_participants')
          .update({
            is_active: false,
            left_at: new Date().toISOString()
          })
          .eq('stream_id', selectedStream.id)
          .eq('user_id', profile?.id)
          .eq('is_active', true)
      }

      setIsConnected(false)
      setSelectedStream(null)
      
    } catch (err: any) {
      console.error('Error leaving stream:', err)
      setError(err.message || 'Failed to leave stream')
    }
  }

  const toggleAudio = () => {
    setAudioEnabled(!audioEnabled)
    // In viewer mode, this would mute/unmute the incoming audio
    // Implementation depends on Agora's audio control API
  }

  useEffect(() => {
    // Cleanup on unmount
    return () => {
      if (agoraService.current && isConnected) {
        leaveStream()
      }
    }
  }, [])

  return (
    <div className="container mx-auto p-4 max-w-6xl">
      <Card>
        <CardHeader>
          <CardTitle>Live Prayer Services</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {!selectedStream ? (
            // Stream selection
            <div className="space-y-4">
              <p className="text-muted-foreground">
                Join live prayer services and Islamic lectures from our scholars and imams
              </p>

              {activeStreams.length === 0 ? (
                <div className="text-center py-12 bg-secondary rounded-lg">
                  <p className="text-muted-foreground">
                    No live streams available at the moment
                  </p>
                  <p className="text-sm text-muted-foreground mt-2">
                    Check back later for prayer times and lectures
                  </p>
                </div>
              ) : (
                <div className="grid gap-4">
                  {activeStreams.map((stream) => (
                    <div
                      key={stream.id}
                      className="p-4 border rounded-lg hover:border-primary transition-colors"
                    >
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="w-2 h-2 bg-destructive rounded-full animate-pulse" />
                            <h3 className="font-semibold text-lg">{stream.title}</h3>
                          </div>
                          <p className="text-sm text-muted-foreground mb-2">
                            by {stream.scholarName}
                          </p>
                          <div className="flex items-center gap-4 text-sm text-muted-foreground">
                            <div className="flex items-center gap-1">
                              <Users className="h-4 w-4" />
                              <span>{stream.viewerCount} watching</span>
                            </div>
                            <span>
                              Started {new Date(stream.startedAt).toLocaleTimeString()}
                            </span>
                          </div>
                        </div>
                        <Button onClick={() => joinStream(stream)}>
                          Join Stream
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ) : (
            // Watching stream
            <div className="space-y-4">
              {/* Stream info */}
              <div className="flex items-center justify-between p-4 bg-secondary rounded-lg">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="w-2 h-2 bg-destructive rounded-full animate-pulse" />
                    <h3 className="font-semibold text-lg">{selectedStream.title}</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    by {selectedStream.scholarName}
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <Users className="h-5 w-5" />
                  <span className="font-bold">{selectedStream.viewerCount}</span>
                </div>
              </div>

              {/* Video player */}
              <div className="relative aspect-video bg-black rounded-lg overflow-hidden">
                <div ref={remoteVideoRef} className="w-full h-full" />
                {!isConnected && (
                  <div className="absolute inset-0 flex items-center justify-center bg-black">
                    <div className="text-white text-center">
                      <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-white mx-auto mb-4"></div>
                      <p>Connecting to stream...</p>
                    </div>
                  </div>
                )}
              </div>

              {/* Viewer controls */}
              <div className="flex items-center justify-between">
                <Button
                  variant={audioEnabled ? 'default' : 'destructive'}
                  onClick={toggleAudio}
                >
                  {audioEnabled ? (
                    <>
                      <Volume2 className="h-4 w-4 mr-2" />
                      Mute
                    </>
                  ) : (
                    <>
                      <VolumeX className="h-4 w-4 mr-2" />
                      Unmute
                    </>
                  )}
                </Button>
                <Button variant="destructive" onClick={leaveStream}>
                  Leave Stream
                </Button>
              </div>

              {error && (
                <div className="p-3 bg-destructive/10 border border-destructive rounded-md">
                  <p className="text-sm text-destructive">{error}</p>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
